import { Inter , Montserrat_Alternates, Poppins } from "next/font/google";
//import { Poppins } from '@/config/fonts';
import "./globals.css";
import TransitionProvider from "@/componentes/transitionProvider";


const poppins = Poppins({ subsets: ["latin"], weight: ['500' , '700'] });

export const metadata = {
  title: "Portafolio Carlos Barrera",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
